#!/bin/bash

# Script para diagnosticar configuración de Meta para Instagram Messaging

echo "🔍 DIAGNÓSTICO DE CONFIGURACIÓN META - INSTAGRAM MESSAGING"
echo "=========================================================="
echo ""

# Colores
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 CHECKLIST DE CONFIGURACIÓN EN META DEVELOPERS${NC}"
echo "   https://developers.facebook.com/apps"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1️⃣  TIPO DE CUENTA DE INSTAGRAM"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${YELLOW}⚠️  REQUISITO CRÍTICO:${NC}"
echo "   La cuenta de Instagram que recibe mensajes DEBE ser:"
echo "   ✅ Cuenta PROFESIONAL (no Personal)"
echo "   ✅ Tipo: EMPRESA (Business) o CREADOR (Creator)"
echo "   ✅ Conectada a una PÁGINA DE FACEBOOK"
echo ""
echo "   ❌ NO funciona con cuentas Personales"
echo ""
echo "   Cómo verificar:"
echo "   1. Abre Instagram → Perfil → Menú (☰)"
echo "   2. Configuración y Privacidad → Tipo de cuenta y herramientas"
echo "   3. Debe decir 'Cuenta Profesional' o 'Cuenta de Empresa'"
echo ""
echo "   Cómo cambiar a Profesional:"
echo "   1. Instagram → Perfil → Menú"
echo "   2. Configuración → Cuenta"
echo "   3. Cambiar a cuenta profesional"
echo "   4. Seleccionar categoría → Empresa"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2️⃣  PÁGINA DE FACEBOOK CONECTADA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${YELLOW}⚠️  REQUISITO CRÍTICO:${NC}"
echo "   Instagram Business requiere una Página de Facebook"
echo ""
echo "   Cómo conectar:"
echo "   1. Instagram → Perfil → Editar Perfil"
echo "   2. Página → Crear una nueva página de Facebook"
echo "   3. O conectar a página existente"
echo ""
echo "   Verificar conexión:"
echo "   1. Instagram → Configuración → Cuenta"
echo "   2. Debe aparecer 'Página de Facebook' conectada"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3️⃣  CONFIGURACIÓN DE WEBHOOKS EN META"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Ir a: https://developers.facebook.com/apps"
echo "   → Tu App → Webhooks"
echo ""
echo -e "${GREEN}Configuración requerida:${NC}"
echo ""
echo "   Callback URL:"
echo "   https://afqbakvvfpebnxzjewsk.supabase.co/functions/v1/instagram-webhook"
echo ""
echo "   Verify Token:"
echo "   d368c7bd78882ba8aae97e480701363127efee4d7f2a2ed79c124fb123d088ec"
echo ""
echo -e "${GREEN}Suscripciones necesarias (checkbox activos):${NC}"
echo "   ✅ messages"
echo "   ✅ messaging_postbacks (opcional)"
echo "   ✅ messaging_optins (opcional)"
echo ""
echo -e "${YELLOW}IMPORTANTE:${NC}"
echo "   Después de configurar, debes SUSCRIBIR la PÁGINA:"
echo "   1. En Webhooks, busca tu Página de Facebook"
echo "   2. Haz clic en 'Subscribe' junto a la página"
echo "   3. Selecciona los campos: messages"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "4️⃣  PERMISOS DE LA APP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Ir a: https://developers.facebook.com/apps"
echo "   → Tu App → App Review → Permissions and Features"
echo ""
echo -e "${GREEN}Permisos necesarios:${NC}"
echo "   ✅ instagram_business_basic (Standard Access)"
echo "   ✅ instagram_business_manage_messages (Standard Access)"
echo "   ✅ pages_manage_metadata (Standard Access)"
echo ""
echo -e "${YELLOW}Nota:${NC} En modo desarrollo, algunos permisos funcionan sin App Review"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "5️⃣  INSTAGRAM TESTERS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Ir a: https://developers.facebook.com/apps"
echo "   → Tu App → Roles → Instagram Testers"
echo ""
echo -e "${GREEN}Pasos:${NC}"
echo "   1. Agregar ambas cuentas como Instagram Testers:"
echo "      - Cuenta que RECIBE mensajes (Business)"
echo "      - Cuenta que ENVÍA mensajes (tester)"
echo ""
echo "   2. Cada cuenta debe ACEPTAR la invitación:"
echo "      Instagram → Configuración → Apps y sitios web"
echo "      → Invitaciones de probador → Aceptar"
echo ""
echo -e "${YELLOW}IMPORTANTE:${NC} Sin aceptar la invitación, NO funcionará"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "6️⃣  VERIFICAR QUE LA PÁGINA ESTÉ VINCULADA A LA APP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Ir a: https://developers.facebook.com/apps"
echo "   → Tu App → Configuración → Básico"
echo "   → Scroll hasta 'Páginas de Facebook'"
echo ""
echo "   La página de Facebook conectada a tu Instagram debe aparecer aquí"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "7️⃣  PROBAR EL WEBHOOK"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Desde la cuenta TESTER, envía un DM a la cuenta BUSINESS:"
echo ""
echo "   📱 Instagram → Buscar la cuenta business"
echo "      → Enviar mensaje: 'Hola, esto es una prueba'"
echo ""
echo -e "${GREEN}Verificar en logs:${NC}"
echo "   Ejecuta en otra terminal:"
echo "   tail -f /var/log/supabase-webhook.log"
echo ""
echo "   O usa la herramienta de Meta:"
echo "   Meta Developers → Tu App → Webhooks → Test"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 RECURSOS ÚTILES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   📖 Instagram Messaging API:"
echo "      https://developers.facebook.com/docs/messenger-platform/instagram"
echo ""
echo "   📖 Webhooks Setup:"
echo "      https://developers.facebook.com/docs/graph-api/webhooks/getting-started"
echo ""
echo "   📖 Instagram Graph API:"
echo "      https://developers.facebook.com/docs/instagram-api"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}✅ PRÓXIMOS PASOS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   1. Verifica que tu cuenta de Instagram sea PROFESIONAL/EMPRESA"
echo "   2. Conecta una Página de Facebook"
echo "   3. Configura el webhook en Meta Developers"
echo "   4. Suscribe la página al webhook"
echo "   5. Agrega testers y acepta invitaciones"
echo "   6. Envía un mensaje de prueba"
echo "   7. Verifica los logs del webhook"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
